### ISSUE TITLE
Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by niieani** [indutny/webpack-common-shake#7]
Hi @indutny! Awesome idea for the plugin. 

I've tried sticking it into our super large app, but we're getting compilation errors:

```
[09:47:51][Step 5/6] uncaughtException TypeError: Cannot read property 'forEach' of null
[09:47:51][Step 5/6]     at Module.mergeFrom (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/common-shake/lib/shake/module.js:54:18)
[09:47:51][Step 5/6]     at Analyzer.resolve (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/common-shake/lib/shake/analyzer.js:52:12)
[09:47:51][Step 5/6]     at NormalModuleFactory.params.normalModuleFactory.plugin (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/webpack-common-shake/lib/shake/plugin.js:55:22)
[09:47:51][Step 5/6]     at NormalModuleFactory.applyPluginsBailResult (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/tapable/lib/Tapable.js:109:27)
[09:47:51][Step 5/6]     at applyPluginsAsyncWaterfall (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/webpack/lib/NormalModuleFactory.js:80:32)
[09:47:51][Step 5/6]     at /home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/tapable/lib/Tapable.js:204:11
[09:47:51][Step 5/6]     at NormalModuleFactory.params.normalModuleFactory.plugin (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
[09:47:51][Step 5/6]     at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/tapable/lib/Tapable.js:208:13)
[09:47:51][Step 5/6]     at resolver (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/webpack/lib/NormalModuleFactory.js:74:11)
[09:47:51][Step 5/6]     at process.nextTick (/home/teamcity/agent-08/3b0ebbb1933d0dce/node_modules/webpack/lib/NormalModuleFactory.js:205:8)
[09:47:51][Step 5/6]     at _combinedTickCallback (internal/process/next_tick.js:134:7)
[09:47:51][Step 5/6]     at process._tickCallback (internal/process/next_tick.js:201:9)
```

We're on Webpack 3 and CommonShakePlugin 1.1.1.

**Comment by indutny** [comment]
Hello!

Thank you for giving it a try! I'm sorry to hear that it didn't work.

I just published a fix for this in `common-shake@1.4.1`. Please run `npm update` to get the latest version. (NOTE: that the fix was introduced into dependency of `webpack-common-shake`, not into the plugin itself! You may want to check `npm ls` after update to make sure that you got the latest).

Thanks again,
Fedor.

**Comment by niieani** [comment]
I've tried the latest version of common-shake, but I'm now getting this error:

```
[08:47:00][Step 5/6] uncaughtException TypeError: this._chunks.sort is not a function
[08:47:00][Step 5/6]     at ReplacementModule.sortItems (/home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/webpack/lib/Module.js:209:17)
[08:47:00][Step 5/6]     at Compilation.sortItemsWithChunkIds (/home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/webpack/lib/Compilation.js:1098:25)
[08:47:00][Step 5/6]     at sealPart2 (/home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/webpack/lib/Compilation.js:610:9)
[08:47:00][Step 5/6]     at Compilation.applyPluginsAsyncSeries (/home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/tapable/lib/Tapable.js:131:46)
[08:47:00][Step 5/6]     at Compilation.seal (/home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/webpack/lib/Compilation.js:578:8)
[08:47:00][Step 5/6]     at /home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/webpack/lib/Compiler.js:510:16
[08:47:00][Step 5/6]     at /home/teamcity/agent-09/3b0ebbb1933d0dce/node_modules/tapable/lib/Tapable.js:225:11
[08:47:00][Step 5/6]     at _combinedTickCallback (internal/process/next_tick.js:134:7)
[08:47:00][Step 5/6]     at process._tickCallback (internal/process/next_tick.js:201:9)
```

Using latest Webpack 3.1.0.

**Comment by indutny** [comment]
Fixed, thank you!
