### ISSUE TITLE
Module parse failed: BASE[type] is not a function

### ISSUE THREAD

**Issue by imathews** [indutny/webpack-common-shake#9]
Thanks for all of the work on this repo. I'm getting the following error when applying the plugin to my (fairly large) react + babel application: 
```
"Module parse failed: /Users/ian/dev/redivis/assets/node_modules/babel-loader/lib/index.js??ref--1!/Users/ian/dev/redivis/assets/javascripts/helpers/bulkUploadUserRequirements.js BASE[type] is not a function
You may need an appropriate loader to handle this file type.
TypeError: BASE[type] is not a function
    at c (/Users/ian/dev/redivis/assets/node_modules/common-shake/lib/shake/walk.js:17:15)
    at Object.skipThrough (/Users/ian/dev/redivis/assets/node_modules/acorn/dist/walk.js:162:39)
    at c (/Users/ian/dev/redivis/assets/node_modules/common-shake/lib/shake/walk.js:17:15)
    at Object.base.VariableDeclarator (/Users/ian/dev/redivis/assets/node_modules/acorn/dist/walk.js:239:20)
    at c (/Users/ian/dev/redivis/assets/node_modules/common-shake/lib/shake/walk.js:17:15)
    at Object.base.VariableDeclaration (/Users/ian/dev/redivis/assets/node_modules/acorn/dist/walk.js:235:7)
    at c (/Users/ian/dev/redivis/assets/node_modules/common-shake/lib/shake/walk.js:17:15)
    at Object.skipThrough (/Users/ian/dev/redivis/assets/node_modules/acorn/dist/walk.js:162:39)
    at c (/Users/ian/dev/redivis/assets/node_modules/common-shake/lib/shake/walk.js:17:15)
    at Object.base.Program.base.BlockStatement (/Users/ian/dev/redivis/assets/node_modules/acorn/dist/walk.js:171:7)"
```

A similar error is being thrown across about a dozen modules; the error message really doesn't make any sense to me. Everything works fine if I remove the plugin.

Let me know if I can provide any further details; many thanks.

**Comment by indutny** [comment]
Sorry about this!

The simplest way to resolve this would be through patching `node_modules/common-shake/lib/shake/walk.js` and adding `console.log(type)` before line 17. Would you care to do it, please?

Thanks for giving it a try! I hope to resolve this for you soon.

**Comment by imathews** [comment]
Not to worry — thanks for the quick follow up!

Based on that log, it seems that type is `'AwaitExpression'` in all instances where the error's being thrown.

FWIW, if I have babel transpile async/await everything works great. Though given that async is now supported in all major browsers, it'd be nice to not necessarily have to transpile...

**Comment by indutny** [comment]
Very interesting! Thank you for the heads up. I'll see what should be done to fix this. (Although, I'm a bit surprised that acorn doesn't have it...)

**Comment by indutny** [comment]
I actually just checked it manually and it appears that `AwaitExpression` is always in `BASE`. Going to try to write a regression test for this. Are you sure that this is the node type that was failing?

**Comment by indutny** [comment]
Just pushed https://github.com/indutny/common-shake/commit/7789eba2ff698308e610ce26d53156bae59bdf56 , appears to be working!

**Comment by imathews** [comment]
hmm...

The line I added at 17 was: 
```
if (typeof BASE[type] !== 'function'){
    console.log('TYPE:', type);
}
```
I wonder if it might be using an older version of acorn... I've been bit by that once before. I'll investigate further and report back

**Comment by indutny** [comment]
Thank you!

**Comment by imathews** [comment]
so it looks like I had acorn ^3.1.0 installed (required by another package) — we need > 5.0 for async support. I noticed that acorn is only listed in devDependencies in this library's package.json; if I move it into dependencies everything works great.

**Comment by indutny** [comment]
Oh gosh, you are right! Should be fixed now!
